# Generated by Django 4.1.5 on 2023-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
